### ISSUE TITLE
Errors with Next 13 app directory

### ISSUE THREAD

**Issue by Adstokoe19** [Fedeya/next-auth-sanity#14]
I'm receiving errors when using the new /app directory in Next 13. I am passing in a client but my IDE is highlighting an issue:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/47350188/208140462-141b9c0d-5f85-4654-8ea0-c4b8a33f34a8.png">

Also, if I use `unstable_getServerSession(authOptions)` as per the nextAuth docs in the /app directory (server component), I get more errors:

```
./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>
```
If I remove the SanityAdapter and SanityCredentials, the errors go away. Have you tested your plugin with Next 13 and the new app directory? 

Thanks.

**Comment by Adstokoe19** [comment]
@Fedeya Do you have an ETA for this fix? Thanks.

**Comment by Fedeya** [comment]
> @Fedeya Do you have an ETA for this fix? Thanks.

Hi @Adstokoe19 for the first problem is a type error of a new version of sanity (now is the 3.x.x), probably i need to change the dependency to a peer dependency for take the latest of the project and avoid this for a new future version of sanity client.
Right now the way for fix this before the patch in the package is
```ts
SanityAdapter(client as any);
```
Or install the version 2.x.x of the sanity client

but for the second one, i tried to replicate that and i can't. 
With the patch i try to make a new example with next 13 in the app directory because i don't get that error

**Comment by Adstokoe19** [comment]
@Fedeya the type error has now gone, thanks!

For the second issue, I think I've fixed it. The [nextAuth docs](https://next-auth.js.org/configuration/nextjs#in-app-directory) suggest:

```
const session = await unstable_getServerSession(authOptions)
```

This gives the error. However, if you remove the argument and use:
```
const session = await unstable_getServerSession()
```
it works as expected.

**Comment by Fedeya** [comment]
@Adstokoe19 oh, i used the `unstable_getServerSession` without the argument of `authOptions` now this makes more sense.

I try to take a look adding that argument, thanks!

**Comment by alec-bfa** [comment]
I'm having the same issue, except if i omit the `authOptions` argument i do not get the custom values I have assigned to the `session.user` object.

I believe this has to do with argon2, as I had the same issue trying to reimplement some of the features into the studio directly. Moving to argon2-wasm fixed the problem in my solution.

Is this still being investigated for a proper solution?

**Comment by Fedeya** [comment]
yes this is an issue with argon2 internally in the package they use the [@mapbox/node-pre-gyp](https://github.com/ranisalt/node-argon2/blob/master/package.json#L49) i tried to solve it with dynamic imports but if you still have the issue in the last version i need to think again of a way to solve this

@alec-bfa while we find a solution, if you want you can send a pr with that workaround to the docs in the readme, it would be very helpful 🙌🏾

**Comment by alecpirillo** [comment]
@Fedeya why not move to [argon2-browser](https://www.npmjs.com/package/argon2-browser)? This would be a fairly quick fix.

**Comment by alec-bfa** [comment]
@Fedeya why not move to [argon2-browser](https://www.npmjs.com/package/argon2-browser)? This would be a fairly quick fix.

**Comment by Fedeya** [comment]
@alec-bfa you should be able to create the pr from your fork but i did it here #17, let me know if that is ready for merge

also for argon i'm doing a research for dependencies to change, thats a good option but looks like has a [lower perfomance in node](https://github.com/antelle/argon2-browser#nodejs-support), i'm looking at [@node-rs/argon2](https://www.npmjs.com/package/@node-rs/argon2) probably for the weekend i release a new version with the fix

**Comment by Fedeya** [comment]
@alec-bfa @Adstokoe19 i tried with the rust bindings and the wasm solutions and they all broke the webpack on the server components

but i found a better workaround, that is [here](https://github.com/Fedeya/next-auth-sanity#app-directory).
this is a sc issue, that's why i made [this pr](https://github.com/vercel/next.js/pull/46779/files) in nextjs repo, with that in the next canary this workaround is no longer needed

**Comment by alecpirillo** [comment]
Great work @Fedeya, much appreciated.
